### ISSUE TITLE
Load the combined CSV to memory and perform a simple EDA

### ISSUE THREAD

**Issue by heidi-ye** [UBC-MDS/group4-525#9]
1. Investigate at least two of the following approaches to reduce memory usage while performing the - - EDA (e.g., value_counts).
- Changing dtype of your data
- Load just columns what we want
- Loading in chunks
- Dask

2. Discuss your observations.

**Comment by JuntingHe** [comment]
- Changing dtype of your data
     - Memory usage with float64: 1499.23 MB
     - Memory usage with float32: 749.61 MB
- Loading in chunks
     - Reduced sys time and thus overall wall time
- Dask
     - The wall time went down with dask and CPU time was higher than wall time
